name: rdl
channels:
  - pytorch
  - gurobi
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - gurobi=9.1.2=py37_0
  - matplotlib=3.4.2=py37h06a4308_0
  - matplotlib-base=3.4.2=py37hab158f2_0
  - numpy=1.20.3=py37hf144106_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - pandas=1.3.3=py37h8c16a72_0
  - scipy=1.7.1=py37h292c36d_2
  - tqdm=4.62.2=pyhd3eb1b0_1